# Generated by Django 3.2.15 on 2022-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='num_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relations',
            name='num_following',
            field=models.IntegerField(default=0),
        ),
    ]
