# Generated by Django 3.2.15 on 2022-12-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_user_relation_prof_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='followers',
        ),
        migrations.AddField(
            model_name='relation',
            name='followers',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='following',
        ),
        migrations.AddField(
            model_name='relation',
            name='following',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
