# Generated by Django 3.2.15 on 2022-12-09 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20221209_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='followers',
            new_name='following_prof_user',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='following',
        ),
        migrations.AlterField(
            model_name='relation',
            name='prof_user',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
