# Generated by Django 3.2.15 on 2022-12-09 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20221209_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='following_prof_user',
        ),
        migrations.AddField(
            model_name='relation',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='prof_user',
        ),
        migrations.AddField(
            model_name='relation',
            name='prof_user',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
