# Generated by Django 3.2.15 on 2022-12-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20221209_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='follower',
            new_name='following',
        ),
        migrations.AddField(
            model_name='relation',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='relation',
            name='prof_user',
        ),
        migrations.AddField(
            model_name='relation',
            name='prof_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
