# Generated by Django 3.2.15 on 2022-12-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20221210_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='network.Post'),
        ),
    ]
