# Generated by Django 3.2.15 on 2022-12-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_user_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='liked_posts',
        ),
    ]
