# Generated by Django 3.2.15 on 2022-10-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchListItem',
            new_name='WatchList',
        ),
    ]
