# Generated by Django 3.2.15 on 2022-10-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_watchlistitem_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='watch_item',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
